name: Run Tests on Push

on:
  push:
    branches:
      - main

env:
  TMDB_API_KEY: "${{ secrets.MY_API_KEY }}"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Run tests
        run: npm test